#!/bin/sh

set -e

# mpirun and mpiexec seemed to be used as a master alternative by some MPI
# package. But currently, all MPI packages have the mpicc alternative installed
# as a slave link. We remove the link here in order to resolve bug #532008,
# #534740, and #544372.

update-alternatives --quiet --remove-all mpirun  >/dev/null 2>&1 || true
update-alternatives --quiet --remove-all mpiexec >/dev/null 2>&1 || true

#DEBHELPER#

exit 0
