#!/bin/sh

set -e

update-alternatives --quiet --remove-all mpiexec >/dev/null 2>&1 || true

update-alternatives \
	--install /usr/bin/mpirun mpirun /usr/bin/mpirun.openmpi 40 \
	--slave /usr/share/man/man1/mpirun.1.gz mpirun.1.gz /usr/share/man/man1/mpirun.openmpi.1.gz \
	--slave /usr/bin/mpiexec mpiexec /usr/bin/mpiexec.openmpi \
	--slave /usr/share/man/man1/mpiexec.1.gz mpiexec.1.gz /usr/share/man/man1/mpiexec.openmpi.1.gz 

#DEBHELPER#

exit 0
